### ISSUE TITLE
Add page container to horizontal-pager

### ISSUE THREAD

**Issue by localnerve** [localnerve/ui-elements#10]
For usability and consistency, it would be good to have the horizontal pager add a page-container to establish a relative outer blocking context for the inner page targets (which rely on absolute).
```css
.page-container {
  position: relative;
  overflow-x: hidden;
  width: 100%;
}
```
